const images = {
  logo: require('~/asset/images/avatar.png'),
  avatarShop: require('~/asset/images/logo_Shop.png'),
  avatarAdmin: require('~/asset/images/avatarAdmin.png'),
  logoShopImg: require('~/asset/images/logo.png'),
  shoes: require('~/asset/images/shoes.jpg'),
  loginImmage: require('~/asset/images/loginImage.jpg').default,

  sofaDa1: require('~/asset/images/sofaDa/sofaDa1.jpg'),
  sofaDa2: require('~/asset/images/sofaDa/sofaDa2.jpg'),
  sofaDa3: require('~/asset/images/sofaDa/sofaDa3.jpg'),
  sofaDa4: require('~/asset/images/sofaDa/sofaDa4.jpg'),
  sofaDa5: require('~/asset/images/sofaDa/sofaDa5.jpg'),
  sofaDa6: require('~/asset/images/sofaDa/sofaDa6.jpg'),
  sofaDa7: require('~/asset/images/sofaDa/sofaDa7.jpg'),
  sofaDa8: require('~/asset/images/sofaDa/sofaDa8.jpg'),
  sofaDa9: require('~/asset/images/sofaDa/sofaDa9.jpg'),
  sofaDa10: require('~/asset/images/sofaDa/sofaDa10.jpg'),
  sofaDa11: require('~/asset/images/sofaDa/sofaDa11.jpg'),
  sofaDa12: require('~/asset/images/sofaDa/sofaDa12.jpg'),
  sofaDa13: require('~/asset/images/sofaDa/sofaDa13.jpg'),
  sofaDa14: require('~/asset/images/sofaDa/sofaDa14.jpg'),
  sofaDa15: require('~/asset/images/sofaDa/sofaDa15.jpg'),
  Doi1: require('~/asset/images/sofaDa/Doi1.jpg'),
  Da1: require('~/asset/images/sofaDa/Da1.jpg'),
  Da2: require('~/asset/images/sofaDa/Da2.jpg'),
  Da3: require('~/asset/images/sofaDa/Da3.jpg'),
  Da4: require('~/asset/images/sofaDa/Da4.jpg'),
  Da5: require('~/asset/images/sofaDa/Da5.jpg'),
  Da6: require('~/asset/images/sofaDa/Da6.jpg'),
  Da7: require('~/asset/images/sofaDa/sofaDa7.jpg'),
  Da8: require('~/asset/images/sofaDa/Da8.jpg'),
  Da9: require('~/asset/images/sofaDa/sofaDa9.jpg'),
  Da10: require('~/asset/images/sofaDa/Da10.jpg'),
  Da11: require('~/asset/images/sofaDa/Da11.jpg'),
  Da12: require('~/asset/images/sofaDa/Da12.jpg'),
  Da13: require('~/asset/images/sofaDa/Da13.jpg'),
  Da14: require('~/asset/images/sofaDa/Da14.jpg'),
  Da15: require('~/asset/images/sofaDa/Da15.jpg'),
  Da16: require('~/asset/images/sofaDa/Da16.jpg'),
  Da17: require('~/asset/images/sofaDa/Da17.jpg'),
  Da18: require('~/asset/images/sofaDa/Da18.jpg'),
  Da19: require('~/asset/images/sofaDa/Da19.jpg'),
  Da20: require('~/asset/images/sofaDa/Da20.jpg'),
  Da21: require('~/asset/images/sofaDa/Da21.jpg'),
  Da22: require('~/asset/images/sofaDa/Da22.jpg'),
  Da23: require('~/asset/images/sofaDa/Da23.jpg'),
  Da24: require('~/asset/images/sofaDa/Da24.jpg'),
  Da25: require('~/asset/images/sofaDa/Da25.jpg'),
  Da26: require('~/asset/images/sofaDa/Da26.jpg'),
  Da27: require('~/asset/images/sofaDa/Da27.jpg'),
  Da28: require('~/asset/images/sofaDa/Da28.jpg'),
  Da29: require('~/asset/images/sofaDa/Da29.jpg'),


  DaHong1: require('~/asset/images/sofaDa/DaHong1.jpg'),
  DaHong2: require('~/asset/images/sofaDa/DaHong2.jpg'),
  DaHong3: require('~/asset/images/sofaDa/DaHong3.jpg'),

  VaiHong1: require('~/asset/images/sofaVai/VaiHong1.jpg'),
  VaiHong2: require('~/asset/images/sofaVai/VaiHong2.jpg'),
  VaiHong3: require('~/asset/images/sofaVai/VaiHong3.jpg'),

  Vai1: require('~/asset/images/sofaVai/Vai1.jpg'),
  Vai2: require('~/asset/images/sofaVai/Vai2.jpg'),
  Vai3: require('~/asset/images/sofaVai/Vai3.jpg'),
  Vai4: require('~/asset/images/sofaVai/Vai4.jpg'),
  Vai5: require('~/asset/images/sofaVai/Vai5.jpg'),
  Vai6: require('~/asset/images/sofaVai/Vai6.jpg'),

  CLDa1: require('~/asset/images/chatLieu/CLDa1.jpg'),
  CLDa2: require('~/asset/images/chatLieu/CLDa2.jpg'),
  CLDa3: require('~/asset/images/chatLieu/CLDa3.jpg'),
  CLDa4: require('~/asset/images/chatLieu/CLDa4.jpg'),
  CLDa5: require('~/asset/images/chatLieu/CLDa5.jpg'),
  CLDa6: require('~/asset/images/chatLieu/CLDa6.jpg'),

  phoneLogo: require('~/asset/images/phoneLogo.png'),
  mesLogo: require('~/asset/images/mesLogo.jpg'),
  zaloLogo: require('~/asset/images/zaloLogo.jpg'),
};

export default images;
